# -*- coding: utf-8 -*-
"""PRODIGY_ML_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgBY377NvlmcCYH78UUh1zUTE8NBK3sf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score, adjusted_rand_score
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv("Mall_Customers.csv")
print("First 5 Rows of Dataset:\n")
print(data.head())
X = data.iloc[:, [3, 4]].values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
k_values = range(1, 11)
wcss = []
silhouette_scores = []

for k in k_values:

    kmeans = KMeans(
        n_clusters=k,
        init='k-means++',
        n_init=10,
        random_state=42
    )

    kmeans.fit(X_scaled)

    wcss.append(kmeans.inertia_)

    if k > 1:
        score = silhouette_score(
            X_scaled,
            kmeans.labels_
        )
        silhouette_scores.append(score)
    else:
        silhouette_scores.append(0)

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values),
    wcss,
    'o-',
    linewidth=2
)

plt.xlabel("Number of Clusters (k)")
plt.ylabel("WCSS")

plt.title("Elbow Method for Optimal k")

plt.grid(True)

plt.show()

plt.figure(figsize=(8, 5))

plt.plot(
    list(k_values)[1:],
    silhouette_scores[1:],
    's-',
    linewidth=2
)

plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")

plt.title("Silhouette Score vs k")

plt.grid(True)

plt.show()

kmeans_final = KMeans(
    n_clusters=5,
    init='k-means++',
    n_init=10,
    random_state=42
)

kmeans_final.fit(X_scaled)

labels = kmeans_final.labels_

centroids = kmeans_final.cluster_centers_

sil_score = silhouette_score(
    X_scaled,
    labels
)

print("\nFinal Model Results")

print("WCSS :", round(kmeans_final.inertia_, 4))

print("Silhouette Score :", round(sil_score, 4))

print("Cluster Sizes :")

for i in range(5):
    print(f"Cluster {i+1} :", sum(labels == i))

x_min = X_scaled[:, 0].min() - 1
x_max = X_scaled[:, 0].max() + 1

y_min = X_scaled[:, 1].min() - 1
y_max = X_scaled[:, 1].max() + 1

xx, yy = np.meshgrid(
    np.linspace(x_min, x_max, 400),
    np.linspace(y_min, y_max, 400)
)

Z = kmeans_final.predict(
    np.c_[xx.ravel(), yy.ravel()]
)

Z = Z.reshape(xx.shape)

colors = ['red', 'blue', 'green', 'purple', 'orange']

markers = ['o', 's', '^', 'D', '*']

plt.figure(figsize=(9, 6))

plt.contourf(xx, yy, Z, alpha=0.25)

for i in range(5):

    plt.scatter(
        X_scaled[labels == i, 0],
        X_scaled[labels == i, 1],
        c=colors[i],
        marker=markers[i],
        edgecolors='black',
        s=60,
        label=f'Cluster {i+1}'
    )

plt.scatter(
    centroids[:, 0],
    centroids[:, 1],
    c='yellow',
    marker='X',
    s=300,
    edgecolors='black',
    label='Centroids'
)

plt.xlabel("Annual Income (Scaled)")
plt.ylabel("Spending Score (Scaled)")

plt.title("K-Means Clustering - Mall Customers Dataset")

plt.legend()

plt.grid(True)

plt.show()

cluster_count = []

for i in range(5):
    cluster_count.append(sum(labels == i))

plt.figure(figsize=(7, 5))

plt.bar(
    [f'C{i+1}' for i in range(5)],
    cluster_count
)

plt.xlabel("Clusters")
plt.ylabel("Number of Customers")

plt.title("Customer Distribution Across Clusters")

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.show()